### ISSUE TITLE
## bug

### ISSUE THREAD

**Issue by TryA9ain** [ph4ntonn/Stowaway#11]
##  bug
finallshell ./linux_x64_admin -h 后，输入命令没有显示
kali ./linux_x64_admin -h 无法使用ctrl+c

**Comment by ph4ntonn** [comment]
感谢您的反馈～补丁已经提交，可以试试最新的release，验证一下是否修复问题
如果已修复，烦请回复我，我会关闭这个issue(笑)

**Comment by TryA9ain** [comment]
> 感谢您的反馈～补丁已经提交，可以试试最新的release，验证一下是否修复问题
> 如果已修复，烦请回复我，我会关闭这个issue(笑)

已经ok了，我顺便就关了
