### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TryA9ain** [ph4ntonn/Stowaway#12]
测试时：当客户端使用重连参数后，ubuntu admin端 shutdown 后，kali 客户端无法使用ctrl+c，linux我只测了kali，没测其他的，不知道其他的linux是否也存在这个问题，windows 客户端则不存在这个问题

**Comment by ph4ntonn** [comment]
测试了Ubuntu 16/18，均无此问题
可能是shell有些问题（平常有时候我也会遇到shell控制字符用不了的情况）
这个问题并不是急需修复，故暂时关闭此issue
感谢反馈～ XD
