### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by TryA9ain** [ph4ntonn/Stowaway#14]
在建立起s5隧道后，使用过程中相对frp感觉不是很稳定，有时候会出现隧道突然断开、过一会又能用的情况。这种情况在不同的目标内网环境我遇到了4次，不排除是我遇到的环境问题。

**Comment by ph4ntonn** [comment]
emmm，感谢你的反馈，但是这样的描述我无法去复现问题，想问问所谓的断开&等一会儿就恢复是否指浏览器代理后有时候无法访问，但什么都不操作，过一会儿又可以正常访问，且期间各节点也没有掉线等异常么

**Comment by TryA9ain** [comment]
> emmm，感谢你的反馈，但是这样的描述我无法去复现问题，想问问所谓的断开&等一会儿就恢复是否指浏览器代理后有时候无法访问，但什么都不操作，过一会儿又可以正常访问，且期间各节点也没有掉线等异常么

给我的感觉就是类似于代理会自动断开一会，然后过一会自己又重新连上

**Comment by ph4ntonn** [comment]
我会尝试复现场景，但不保证一定能遇见相同的状况
如果有师傅们看见这个issue，并有同样的问题，欢迎在此issue下留言并提供给我更为详细，更加稳定的复现方式
再次感谢反馈～
