### ISSUE TITLE
windows agent出现问题

### ISSUE THREAD

**Issue by TryA9ain** [ph4ntonn/Stowaway#16]
### 今天我从releases 下载windows64 agent ，使用出现了错误
![image](https://user-images.githubusercontent.com/51145610/126924190-02fc349c-82d4-4c98-b00d-9a21f19fba97.png)
![image](https://user-images.githubusercontent.com/51145610/126924241-854aec81-8760-4008-8ca4-d89d285b5916.png)
![image](https://user-images.githubusercontent.com/51145610/126924213-c7b2c987-b650-42bb-afa5-7c8aa4fa8891.png)

**Comment by ph4ntonn** [comment]
确定admin和agent都是最新的么

**Comment by TryA9ain** [comment]
> 确定admin和agent都是最新的么
