### ISSUE TITLE
不支持winxp和2003版本，怎么办，是自行编译吗

### ISSUE THREAD

**Issue by Clear2020** [ph4ntonn/Stowaway#17]
不支持winxp和2003版本，怎么办，是自行编译吗

**Comment by ph4ntonn** [comment]
抱歉没看见issue（捂脸
如果要在低版本win上运行，请使用go 1.10.8版本进行编译，高版本go无法在2003上运行（xp没测试过，应当也是如此）

**Comment by Clear2020** [comment]
好的，谢谢大佬

**Comment by ph4ntonn** [comment]
没事～很高兴能帮助到你～

**Comment by Cyc1e183** [comment]
师傅编译成功木有？
