### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ffsfwnuiaww** [ph4ntonn/Stowaway#18]
进入shell之后，无法中断命令

![image](https://user-images.githubusercontent.com/89639412/135244321-323f62f1-b87c-4758-b13d-e937196ecc4d.png)

使用control + c 根本没办法中断，，，，输入exit 也退出不了 永久卡死在这里了

![image](https://user-images.githubusercontent.com/89639412/135244572-ce0cdab7-aea3-456e-b41d-695640fdc6e1.png)

**Comment by ph4ntonn** [comment]
不好意思，如果方便的话，请描述admin & agent环境，以及相关细节
另外，请问还能稳定复现么？
谢谢～

**Comment by ffsfwnuiaww** [comment]
遇到了很多次了，admin环境centos，kali 都用过，agent环境也都用过。

这个问题我朋友也遇到过很多次

你可以测试，agent了之后，ping任意一个ip 然后不指定次数 

这样就会永久循环 ，，无法结束 永远卡死到这里了

**Comment by ph4ntonn** [comment]
不好意思，这个shell不是可交互式的，我特地在README中未提到**交互式**
故而不可以运行类似您提到的```ping任意一个ip 然后不指定次数```这样的命令
交互式终端编写起来比较麻烦，如果有好的解决方案 & 代码，欢迎pr
谢谢～
