### ISSUE TITLE
编译和建议

### ISSUE THREAD

**Issue by xixuedafa** [ph4ntonn/Stowaway#2]
我在win32下编译的时候，编译出来命令要加空格再回车才能用
我打出来命令前面有个]不知道为什么
use 1这种 因为代码里面是"1"，所以用字符串截取才能用
用手机上的termux编译，则没有上面的问题，还好go是交叉编译的，编译好放win32下就没有上面的问题
你有个注释，main.go 里面 如果要编译admin的话，除了把agent注释了，admin不注释，上面的import的agnet要改成admin吧。
这个玩意要是能把节点端口监听流量转发回来监听就更好了，虽然可以frp，感觉用了这个再用frp总是有些麻烦，ssh虽然也行，但也不是什么平台上都有的。

**Comment by ph4ntonn** [comment]
> 我在win32下编译的时候，编译出来命令要加空格再回车才能用
> 我打出来命令前面有个]不知道为什么
> use 1这种 因为代码里面是"1"，所以用字符串截取才能用
> 用手机上的termux编译，则没有上面的问题，还好go是交叉编译的，编译好放win32下就没有上面的问题
> 你有个注释，main.go 里面 如果要编译admin的话，除了把agent注释了，admin不注释，上面的import的agnet要改成admin吧。
> 这个玩意要是能把节点端口监听流量转发回来监听就更好了，虽然可以frp，感觉用了这个再用frp总是有些麻烦，ssh虽然也行，但也不是什么平台上都有的。

  谢谢您的建议，首先编译上的问题，在win32下编译运行我没有试过（手头没有环境），看您的描述，可能是您win32下编译环境的问题？我之后会视情况加上编译测试好的win32程序。另外，那个注释的问题。。。确实是我的失误，因为vs code会自动补全。。XD ,所以忘了上面import的问题，我会更改一下注释的。最后，您说的这个功能的意思，我理解的是，在一个节点上监听一个端口，并将这个端口上收到的数据转发回admin端，不知道我理解的是否正确？
  最后还是谢谢您的建议～

**Comment by xixuedafa** [comment]
win32那个无所谓，可能我那个xp的系统...太老了…...linux反正能编译出来也能给windows用就行了。
那个转发是我说的意思，没错没错。:)

**Comment by ph4ntonn** [comment]
> win32那个无所谓，可能我那个xp的系统...太老了…...linux反正能编译出来也能给windows用就行了。
> 
> 我过去用过不少转发的工具，我发现如果转发的内容有不可见字符啥的，大多数现代的转发工具就用不了，过去老的c语言写的lcx啥的可以，frp，ssh的转发，系统自带的转发也都是可以的，这样就出现可以多节点的软件转发不行，能转发的软件用在复杂的网络环境下很难用。
> 
> 那个转发是我说的意思，没错没错。:)

。。。抱歉我才看到你的回复，我后期会考虑加上你所说的功能的 XD
谢谢您的建议哈哈 :)
