### ISSUE TITLE
agent 连接的时候，admin 端出现了错误

### ISSUE THREAD

**Issue by truda8** [ph4ntonn/Stowaway#25]
agent 和 admin 均是最新版

![image](https://user-images.githubusercontent.com/30512942/141614068-d88f6043-f00c-401e-ab93-66aba4de68a8.png)

**Comment by ph4ntonn** [comment]
十分抱歉，最近比较忙，等空下来会和pr一起修复的

**Comment by ph4ntonn** [comment]
不好意思，我刚试了一下，没有复现这个情况，请问能稳定复现嘛？如果不能，我晚上回去看一下详细的代码～
