### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by Tukali** [ph4ntonn/Stowaway#28]
基本配置：主节点监听端口，服务端主动连接主节点；主节点开启listen，子节点主动连接

1.listen 监听的端口无法关闭，在主节点上开启的监听端口无法连接或连接中断后，无法删除不需要的listen

2.socks通道代理不稳定，使用二级子节点创建socks通道，连接1分钟后服务器直接断开，再次登录发现，主节点已经连接不上
<img width="703" alt="CleanShot 2022-02-24 at 10 43 39@2x" src="https://user-images.githubusercontent.com/45891208/155447569-a516dc07-8a66-47f1-b330-ee9149779429.png">
登录主节点查看后发现，主节点的进程正常，端口也开放，time wait

**Comment by ph4ntonn** [comment]
好的，那这个issue就暂时关闭了，如果有师傅可以稳定复现，请在本issue下留言，reopen这个issue，感谢～
同时也感谢你的反馈～
