### ISSUE TITLE
UDP特性

### ISSUE THREAD

**Issue by zer0yu** [ph4ntonn/Stowaway#3]
想问一下是否支持UDP流量的代理呢？

**Comment by ph4ntonn** [comment]
> 想问一下是否支持UDP流量的代理呢？

暂时还不支持(用得少所以就没加

后面有空就会更新 ：）

你这边的代理是指单端口的转发？还是socks？

**Comment by zer0yu** [comment]
> > 想问一下是否支持UDP流量的代理呢？
> 
> 暂时还不支持(用得少所以就没加
> 
> 后面有空就会更新 ：）
> 
> 你这边的代理是指单端口的转发？还是socks？

socks的udp
用到了突然发现不支持，期待后续的更新

**Comment by ph4ntonn** [comment]
> > > 想问一下是否支持UDP流量的代理呢？
> 
> > 
> 
> > 暂时还不支持(用得少所以就没加
> 
> > 
> 
> > 后面有空就会更新 ：）
> 
> > 
> 
> > 你这边的代理是指单端口的转发？还是socks？
> 
> 
> 
> socks的udp
> 
> 用到了突然发现不支持，期待后续的更新

我尽量早些添加支持 ^_^
感谢你的建议～

**Comment by ph4ntonn** [comment]
已添加支持～
