### ISSUE TITLE
用cs将agent传至win10 运行命令后被defender杀

### ISSUE THREAD

**Issue by Po3son** [ph4ntonn/Stowaway#32]
用cs将agent传至win10 运行命令后被defender杀 ，请问大佬是姿势不对，还是需自行修改免杀

**Comment by ph4ntonn** [comment]
您好，本工具不包含免杀，免杀姿势请自行探索
另外，release下的agent为upx压缩后的agent，upx壳容易被杀，可以试试直接编译来绕过杀软，缺点是文件体积会变大不少，请看情况使用
