### ISSUE TITLE
 隐藏工具进程参数

### ISSUE THREAD

**Issue by Po3son** [ph4ntonn/Stowaway#33]
请问师傅有无隐藏agent进程的功能，防守方可查看ps aux和history查看到-c 的ip与端口还有-s秘钥，有什么方法能隐藏这些参数吗

**Comment by ph4ntonn** [comment]
若希望隐藏参数，可直接硬编码参数后自行编译agent

**Comment by ph4ntonn** [comment]
如果一定要隐藏进程请参考rootkit
