### ISSUE TITLE
希望支持mac m1芯片

### ISSUE THREAD

**Issue by killdayu** [ph4ntonn/Stowaway#35]
希望支持一下mac m1芯片，🙏

**Comment by ph4ntonn** [comment]
我会在之后的commit中提交
但还是希望您能善加利用google进行查阅，这根本不是什么很费时间的操作，谢谢

**Comment by killdayu** [comment]
> 我会在之后的commit中提交 但还是希望您能善加利用google进行查阅，这根本不是什么很费时间的操作，谢谢

抱歉，我只是想获得官方的支持，因为我之前编译其他go写的软件的m1版本会出现bug。

**Comment by ph4ntonn** [comment]
好吧哈哈，我只有intel版本的mac，不太了解m1用户的痛(手动狗头
不好意思说话可能冲了点，我以为又是伸手党orz
您可以试试是否有bug，如果有的话欢迎在issue中反馈，感谢~

**Comment by killdayu** [comment]
> 好吧哈哈，我只有intel版本的mac，不太了解m1用户的痛(手动狗头 不好意思说话可能冲了点，我以为又是伸手党orz 您可以试试是否有bug，如果有的话欢迎在issue中反馈，感谢~

好的，等会晚上有空我编译试试

**Comment by killdayu** [comment]
> > 好吧哈哈，我只有intel版本的mac，不太了解m1用户的痛(手动狗头 不好意思说话可能冲了点，我以为又是伸手党orz 您可以试试是否有bug，如果有的话欢迎在issue中反馈，感谢~
> 
> 好的，等会晚上有空我编译试试

运行正常，感谢作者的开源

**Comment by ph4ntonn** [comment]
没事，也感谢您的测试~
