### ISSUE TITLE
不出网，反代主机如何使用该代理程序

### ISSUE THREAD

**Issue by Po3son** [ph4ntonn/Stowaway#36]
不出网且存在反代机器能使用这个代理做端口复用然后连接外网ip吗,或者可以使用什么功能达到代理转发

**Comment by ph4ntonn** [comment]
存在反代的情况下由于端口复用的实现原理的原因不推荐使用端口复用，端口复用一般多在内网，即第二层及以后的节点使用
如果第一层完全不出网，且有反代，个人觉得一般还是使用类似regeorg这类代理做第一层，后续的层级搭建就可以依靠第一层的代理来使用admin主动连接模式来构造
