### ISSUE TITLE
代理支持

### ISSUE THREAD

**Issue by SignorMercurio** [ph4ntonn/Stowaway#4]
请问是否会考虑添加代理支持呢？例如在 admin 连接 agent 或 agent 连接 admin 时，可以用 --proxy 选项来使用 SOCKS 或者 HTTP 代理。

**Comment by ph4ntonn** [comment]
> 请问是否会考虑添加代理支持呢？例如在 admin 连接 agent 或 agent 连接 admin 时，可以用 --proxy 选项来使用 SOCKS 或者 HTTP 代理。

可以的～
不过我暂时没有空来添加这一功能
如果图方便引入第三方库的话会导致编译后的文件过大(现在已经不小了)
不介意大小的话可以自己在node/init.go中的StartNodeConn函数下修改Dial的逻辑，引入第三方库来实现agent端的代理
在admin/admin.go中的ConnectToStartNode函数下修改Dial的逻辑，实现admin端的代理
如果比较介意大小，那估计要稍等等，暂时我没有时间来改～
ps：HTTP代理是不行的，只能支持socks5

**Comment by SignorMercurio** [comment]
> > 请问是否会考虑添加代理支持呢？例如在 admin 连接 agent 或 agent 连接 admin 时，可以用 --proxy 选项来使用 SOCKS 或者 HTTP 代理。
> 
> 可以的～
> 不过我暂时没有空来添加这一功能
> 如果图方便引入第三方库的话会导致编译后的文件过大(现在已经不小了)
> 不介意大小的话可以自己在node/init.go中的StartNodeConn函数下修改Dial的逻辑，引入第三方库来实现agent端的代理
> 在admin/admin.go中的ConnectToStartNode函数下修改Dial的逻辑，实现admin端的代理
> 如果比较介意大小，那估计要稍等等，暂时我没有时间来改～
> ps：HTTP代理是不行的，只能支持socks5

感谢回复~我尝试一下

**Comment by ph4ntonn** [comment]
> > > 请问是否会考虑添加代理支持呢？例如在 admin 连接 agent 或 agent 连接 admin 时，可以用 --proxy 选项来使用 SOCKS 或者 HTTP 代理。
> > 
> > 
> > 可以的～
> > 不过我暂时没有空来添加这一功能
> > 如果图方便引入第三方库的话会导致编译后的文件过大(现在已经不小了)
> > 不介意大小的话可以自己在node/init.go中的StartNodeConn函数下修改Dial的逻辑，引入第三方库来实现agent端的代理
> > 在admin/admin.go中的ConnectToStartNode函数下修改Dial的逻辑，实现admin端的代理
> > 如果比较介意大小，那估计要稍等等，暂时我没有时间来改～
> > ps：HTTP代理是不行的，只能支持socks5
> 
> 感谢回复~我尝试一下

已经实现了这个功能～感谢issue～
