### ISSUE TITLE
某个节点开启端口转发之后，在切换到其他节点开启端口转发bug

### ISSUE THREAD

**Issue by zyylhn** [ph4ntonn/Stowaway#41]
某个节点开启端口转发之后，在切换到其他节点开启端口转发的话，manager.forwardMap会被重新make，导致之前的记录被删掉，并且listener没有被关掉，会导致addconn函数爆空指针异常。
https://github.com/ph4ntonn/Stowaway/blob/67f6fabbadff8478e5d1bafd73af9fadc708b8ca/admin/manager/forward.go#L123
建议注视掉这一行，在新建manager的时候就已经make了，不需要重新make

**Comment by ph4ntonn** [comment]
已经确定了此问题会同时在forward&backward中出现，是我疏忽了
今晚即会更新代码及release
感谢师傅的反馈~

**Comment by ph4ntonn** [comment]
已在https://github.com/ph4ntonn/Stowaway/commit/366d6a5c81ea8a50d02c8eedbc1c0b073fe1c602 中修复此问题
再次感谢师傅~
