### ISSUE TITLE
有概率无法退出shell

### ISSUE THREAD

**Issue by vvone123** [ph4ntonn/Stowaway#44]
在Centos用screen运行linux_x64_admin，在节点运行shell，有时候会卡住退不出来，只能kill进程。
![image](https://user-images.githubusercontent.com/50262716/188333958-c62336a7-90cf-40b1-9ca4-8003919fffd0.png)

**Comment by ph4ntonn** [comment]
感谢师傅反馈，仔细看了下代码，暂时没找到问题所在
会持续关注此问题，复现成功后会尽快修复此类bug

**Comment by N0el4kLs** [comment]
遇到这种阻塞性的任务会出现无法取消的情况，想问下这种情况有什么能够强制退出的解决方案吗
![image](https://user-images.githubusercontent.com/64629436/206096067-111152ca-b55a-40ba-8226-34b5742d922b.png)

**Comment by ph4ntonn** [comment]
> 遇到这种阻塞性的任务会出现无法取消的情况，想问下这种情况有什么能够强制退出的解决方案吗
> 
> ![image](https://user-images.githubusercontent.com/64629436/206096067-111152ca-b55a-40ba-8226-34b5742d922b.png)
> 
> 

阻塞性任务是这样的，但nc连接上以后也无法退出么？

**Comment by N0el4kLs** [comment]
> > 遇到这种阻塞性的任务会出现无法取消的情况，想问下这种情况有什么能够强制退出的解决方案吗
> > ![image](https://user-images.githubusercontent.com/64629436/206096067-111152ca-b55a-40ba-8226-34b5742d922b.png)
> 
> 阻塞性任务是这样的，但nc连接上以后也无法退出么？

如果连上nc得的话，另一端ctrl+c 退出后 这边也会跟着退出，这没什么问题。 但是像遇到需要开python server 或者nc开启监听后没有连接这种情况 ，如果没法主动退出会一直阻塞， 也没办法回退到控制端，很难受。

**Comment by honeypothoneypot** [comment]
是这样的，我也遇到过

**Comment by tomsux** [comment]
> > > 遇到这种阻塞性的任务会出现无法取消的情况，想问下这种情况有什么能够强制退出的解决方案吗
> > > ![image](https://user-images.githubusercontent.com/64629436/206096067-111152ca-b55a-40ba-8226-34b5742d922b.png)
> > 
> > 
> > 阻塞性任务是这样的，但nc连接上以后也无法退出么？
> 
> 如果连上nc得的话，另一端ctrl+c 退出后 这边也会跟着退出，这没什么问题。 但是像遇到需要开python server 或者nc开启监听后没有连接这种情况 ，如果没法主动退出会一直阻塞， 也没办法回退到控制端，很难受。

python3 -m http.server 我也遇到了,只能重启服务吗

**Comment by ph4ntonn** [comment]
Add force quit option under shell/ssh mode https://github.com/ph4ntonn/Stowaway/commit/14a6bd375fcb97f1af41633185b2d4d56bc17620
