### ISSUE TITLE
 syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by Padavan2019** [ph4ntonn/Stowaway#47]
![image](https://user-images.githubusercontent.com/58964582/204087850-e506c5b4-d360-41af-9381-385be7ada24c.png)

**Comment by ph4ntonn** [comment]
这看上去是bash的问题，和程序应该无关...

**Comment by ph4ntonn** [comment]
请检查一下是否输入了什么不可见字符或者bash是否有问题
