### ISSUE TITLE
多级反向socks5代理

### ISSUE THREAD

**Issue by GJHcmyk** [ph4ntonn/Stowaway#5]
Hi，感谢师傅做出了这么好用的工具！

我注意到当`goto`某个节点之后，运行`socks [lport]`会在该节点启动socks服务器，然后将admin端`lport`的流量转发过去。请问是否会有一个反向的类似功能呢？即在admin端启动socks服务器，然后将某个agent节点某端口的流量转发到admin端。

（这个应该算`enhancement`吧）

**Comment by ph4ntonn** [comment]
> Hi，感谢师傅做出了这么好用的工具！
> 
> 我注意到当`goto`某个节点之后，运行`socks [lport]`会在该节点启动socks服务器，然后将admin端`lport`的流量转发过去。请问是否会有一个反向的类似功能呢？即在admin端启动socks服务器，然后将某个agent节点某端口的流量转发到admin端。
> 
> （这个应该算`enhancement`吧）

emmmm，我没有太理解这句```即在admin端启动socks服务器，然后将某个agent节点某端口的流量转发到admin端```.
不过以我的理解(加猜测)，stowaway有个命令，reflect [rport] [lport]，不知道是否就是你想要的功能  :)。

**Comment by GJHcmyk** [comment]
> > Hi，感谢师傅做出了这么好用的工具！
> > 我注意到当`goto`某个节点之后，运行`socks [lport]`会在该节点启动socks服务器，然后将admin端`lport`的流量转发过去。请问是否会有一个反向的类似功能呢？即在admin端启动socks服务器，然后将某个agent节点某端口的流量转发到admin端。
> > （这个应该算`enhancement`吧）
> 
> emmmm，我没有太理解这句`即在admin端启动socks服务器，然后将某个agent节点某端口的流量转发到admin端`.
> 不过以我的理解(加猜测)，stowaway有个命令，reflect [rport] [lport]，不知道是否就是你想要的功能 :)。

就是现有的socks命令会在agent上启动socks服务，然后可以通过admin上的某个端口访问到该服务；上面提到的功能和这个相反，在admin上启动socks服务，然后可以通过agent上的某个端口访问到该服务。

然后我之前另起一个socks服务器后测试了`reflect`命令（转发TCP/1080端口），发现虽然代理TCP流量时可以达到效果，不过代理UDP流量似乎就不行了，可能是因为UDP Associate实现时需要额外监听UDP端口，而这个UDP端口无法被`reflect`端口转发过去。

**Comment by ph4ntonn** [comment]
> > > Hi，感谢师傅做出了这么好用的工具！
> > > 我注意到当`goto`某个节点之后，运行`socks [lport]`会在该节点启动socks服务器，然后将admin端`lport`的流量转发过去。请问是否会有一个反向的类似功能呢？即在admin端启动socks服务器，然后将某个agent节点某端口的流量转发到admin端。
> > > （这个应该算`enhancement`吧）
> > 
> > 
> > emmmm，我没有太理解这句`即在admin端启动socks服务器，然后将某个agent节点某端口的流量转发到admin端`.
> > 不过以我的理解(加猜测)，stowaway有个命令，reflect [rport] [lport]，不知道是否就是你想要的功能 :)。
> 
> 就是现有的socks命令会在agent上启动socks服务，然后可以通过admin上的某个端口访问到该服务；上面提到的功能和这个相反，在admin上启动socks服务，然后可以通过agent上的某个端口访问到该服务。
> 
> 然后我之前另起一个socks服务器后测试了`reflect`命令（转发TCP/1080端口），发现虽然代理TCP流量时可以达到效果，不过代理UDP流量似乎就不行了，可能是因为UDP Associate实现时需要额外监听UDP端口，而这个UDP端口无法被`reflect`端口转发过去。

唔，我明白你的意思了
能问下有什么使用场景么，因为说实在的，你所说的udp流量反向代理第一是实战中极少用到(至少我所了解的，甚至使用udp流量并支持socks5的工具我都没咋见过)，第二是本身也不建议代理udp流量，很多socks5客户端也并没有按照标准rfc文档实现
所以如果没有很普适的使用场景，我可能并不会加入此功能，防止客户端体积进一步无意义地增大

**Comment by ph4ntonn** [comment]
> > > > > Hi，感谢师傅做出了这么好用的工具！
> > > > > 我注意到当`goto`某个节点之后，运行`socks [lport]`会在该节点启动socks服务器，然后将admin端`lport`的流量转发过去。请问是否会有一个反向的类似功能呢？即在admin端启动socks服务器，然后将某个agent节点某端口的流量转发到admin端。
> > > > > （这个应该算`enhancement`吧）
> > > > 
> > > > 
> > > > emmmm，我没有太理解这句`即在admin端启动socks服务器，然后将某个agent节点某端口的流量转发到admin端`.
> > > > 不过以我的理解(加猜测)，stowaway有个命令，reflect [rport] [lport]，不知道是否就是你想要的功能 :)。
> > > 
> > > 
> > > 就是现有的socks命令会在agent上启动socks服务，然后可以通过admin上的某个端口访问到该服务；上面提到的功能和这个相反，在admin上启动socks服务，然后可以通过agent上的某个端口访问到该服务。
> > > 然后我之前另起一个socks服务器后测试了`reflect`命令（转发TCP/1080端口），发现虽然代理TCP流量时可以达到效果，不过代理UDP流量似乎就不行了，可能是因为UDP Associate实现时需要额外监听UDP端口，而这个UDP端口无法被`reflect`端口转发过去。
> > 
> > 
> > 唔，我明白你的意思了
> > 能问下有什么使用场景么，因为说实在的，你所说的udp流量反向代理第一是实战中极少用到(至少我所了解的，甚至使用udp流量并支持socks5的工具我都没咋见过)，第二是本身也不建议代理udp流量，很多socks5客户端也并没有按照标准rfc文档实现
> > 所以如果没有很普适的使用场景，我可能并不会加入此功能，防止客户端体积进一步无意义地增大
> 
> 好的，目前我好像也没有很具体的使用场景，就是想问一下基于工具现有功能是否可以实现，感谢师傅回答~

没事～
其实实现起来并不是很复杂，但是程序会进一步臃肿
如果你能有比较具体可用的场景，我可能会将```reflect```分为```reflectudp```和```reflecttcp```，因为socks5的实现代码比较复杂，reflect则更加轻便
Anyway，谢谢你的支持～也欢迎继续提出pr和issue～

**Comment by GJHcmyk** [comment]
> > > > > > Hi，感谢师傅做出了这么好用的工具！
> > > > > > 我注意到当`goto`某个节点之后，运行`socks [lport]`会在该节点启动socks服务器，然后将admin端`lport`的流量转发过去。请问是否会有一个反向的类似功能呢？即在admin端启动socks服务器，然后将某个agent节点某端口的流量转发到admin端。
> > > > > > （这个应该算`enhancement`吧）
> > > > > 
> > > > > 
> > > > > emmmm，我没有太理解这句`即在admin端启动socks服务器，然后将某个agent节点某端口的流量转发到admin端`.
> > > > > 不过以我的理解(加猜测)，stowaway有个命令，reflect [rport] [lport]，不知道是否就是你想要的功能 :)。
> > > > 
> > > > 
> > > > 就是现有的socks命令会在agent上启动socks服务，然后可以通过admin上的某个端口访问到该服务；上面提到的功能和这个相反，在admin上启动socks服务，然后可以通过agent上的某个端口访问到该服务。
> > > > 然后我之前另起一个socks服务器后测试了`reflect`命令（转发TCP/1080端口），发现虽然代理TCP流量时可以达到效果，不过代理UDP流量似乎就不行了，可能是因为UDP Associate实现时需要额外监听UDP端口，而这个UDP端口无法被`reflect`端口转发过去。
> > > 
> > > 
> > > 唔，我明白你的意思了
> > > 能问下有什么使用场景么，因为说实在的，你所说的udp流量反向代理第一是实战中极少用到(至少我所了解的，甚至使用udp流量并支持socks5的工具我都没咋见过)，第二是本身也不建议代理udp流量，很多socks5客户端也并没有按照标准rfc文档实现
> > > 所以如果没有很普适的使用场景，我可能并不会加入此功能，防止客户端体积进一步无意义地增大
> > 
> > 
> > 好的，目前我好像也没有很具体的使用场景，就是想问一下基于工具现有功能是否可以实现，感谢师傅回答~
> 
> 没事～
> 其实实现起来并不是很复杂，但是程序会进一步臃肿
> 如果你能有比较具体可用的场景，我可能会将`reflect`分为`reflectudp`和`reflecttcp`，因为socks5的实现代码比较复杂，reflect则更加轻便
> Anyway，谢谢你的支持～也欢迎继续提出pr和issue～

嗯嗯，感觉`reflectudp`会更泛用一点，既能解决上面的问题，也可以满足其它需要udp远程端口转发的场景，比如让agent使用admin上的DNS服务器等。
