### ISSUE TITLE
关于编译免杀

### ISSUE THREAD

**Issue by Vikec** [ph4ntonn/Stowaway#51]
agent 使用garble编译可以过大部分杀软但是使用时连接主控端会弹出这个异常
<img width="403" alt="2023-05-07_14-33-26" src="https://user-images.githubusercontent.com/16778958/236661838-3b215e64-072f-4e1f-82a6-2998e8dadcea.png">

**Comment by ph4ntonn** [comment]
不好意思，这个看上去应该是garble混淆时出现的错误，我对garble这个项目也不太了解，可能暂时无法修复这个问题
如果有解决方案，也欢迎pr或者在issue下留言赐教
