### ISSUE TITLE
一个端口无法上线多个目标

### ISSUE THREAD

**Issue by cqrlhz** [ph4ntonn/Stowaway#52]
./agent -c x.x.x.x:7500 -s cqmyg --reconnect 120
2023/05/15 00:17:40 [*] Starting agent node actively.Connecting to x.x.x.x:7500.Reconnecting every 120 seconds
2023/05/15 00:17:47 [*] Error occured: dial tcp x.x.x.x:7500: connect: connection refused

一个目标上线后，其他目标无法上线，需要重开其他端口才能上线

**Comment by ph4ntonn** [comment]
这个不是bug
此设计原本是为了强制使用者分离不同的出网通路，防止不同的出网通路相互存在关联
但确实此设计会让使用者用起来比较麻烦一些
这个应该暂时不会修改，也欢迎师傅们pr相关功能
