### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dirchen-admin** [ph4ntonn/Stowaway#53]
agent版本：gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
无法上线，admin端报错
![图片](https://github.com/ph4ntonn/Stowaway/assets/70562364/e57c1c25-ecc8-4673-b9d5-f6c2d9c37b5e)

**Comment by ph4ntonn** [comment]
admin和agent启动参数是什么？

**Comment by dirchen-admin** [comment]
> admin和agent启动参数是什么？

./admin -l 10000

**Comment by dirchen-admin** [comment]
> admin和agent启动参数是什么？

./admin -l 10000
./agent -c x.x.x.x:10000
