### ISSUE TITLE
backward使用问题

### ISSUE THREAD

**Issue by fullstackcainiao** [ph4ntonn/Stowaway#54]
使用场景：本机Windows11为admin，使用vps作为agent节点0，内网一台win11作为节点0的子节点1，在admin上use1，
如下将节点1的3389端口转发到本机的43389
![image](https://github.com/ph4ntonn/Stowaway/assets/54357723/c3b0605d-82e6-42ab-87e3-68168f57bde5)

实际效果并没有转发成功，是我都操作有问题吗。。

**Comment by ph4ntonn** [comment]
backward 3389 43389才是将节点1的3389端口映射到本机的43389

**Comment by ph4ntonn** [comment]
你主机上本来就没有正在监听43389的服务，反向映射并不会在本机上监听端口，而是在agent上监听端口

**Comment by ph4ntonn** [comment]
这个监听43389的服务是要你自己起的，和stowaway没关系
