### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by fullstcat** [ph4ntonn/Stowaway#55]
使用场景：admin为本机win11，node 0 为公网VPS，node 1为内网一台win 11，使用VPS agent被动监听，本机admin主动连接VPS，再node 0 listen 40081，内网win11 agent 主动连接node 0节点，上线成功，此时再次使用node 0 listen后上线内网其他机器失败如下：

![image](https://github.com/ph4ntonn/Stowaway/assets/54357723/8852ae32-b002-403f-86ec-20aad5014884)

（网络非常坚挺，排除网络问题），测试内网win11,win10,在此情况下都无法上线

**Comment by ph4ntonn** [comment]
自己测试过了，没复现这个问题
另外看图上打印的信息应该和软件无关，可以试试检查下防火墙之类的设置
