### ISSUE TITLE
管理端掉线不会自动重新建立廉价而

### ISSUE THREAD

**Issue by xigagas** [ph4ntonn/Stowaway#60]
![image](https://github.com/ph4ntonn/Stowaway/assets/139865587/73b587d2-5771-4eed-a8ed-10473d7ebc08)
admin一天掉一次线，即使agent设置重连  ，admin端也不会自动重新连接，等重新打开admin端才可以接收连接

**Comment by ph4ntonn** [comment]
Hi～
admin确实是这么设计的，暂时不会对这个行为进行修改
如果一直掉线，可以试试—heartbeat开启心跳包保活试一试
