### ISSUE TITLE
windows server2008运行出错

### ISSUE THREAD

**Issue by lem0n817** [ph4ntonn/Stowaway#64]
如图，windows2008 64位和windows 764位都报的这个错误，这是什么原因？
![image](https://github.com/ph4ntonn/Stowaway/assets/172578979/eda91f8a-9d47-475b-ae98-36916146172c)

**Comment by ph4ntonn** [comment]
请自行使用go 1.21之前的版本编译，release中的版本比较新

**Comment by ph4ntonn** [comment]
为了保证最良好的兼容性，已更新release中的版本为1.20版本，可以再试一下

**Comment by lem0n817** [comment]
> 为了保证最良好的兼容性，已更新release中的版本为1.20版本，可以再试一下

可以正常使用了，谢谢师傅
