### ISSUE TITLE
节点中运行一个程序没结束就退不出来

### ISSUE THREAD

**Issue by shao65308** [ph4ntonn/Stowaway#66]
当节点中运一个命令，不知道如何终止这个命令
按ctrl+c提示：[*]Please use 'exit' to exit shell/sshmode

不知道怎么才能退出或返回

**Comment by ph4ntonn** [comment]
首先，不要在shell模式中使用阻塞命令
另外你用的是最新的release吗(大版本号没变，但是release一直有更新)？

**Comment by ph4ntonn** [comment]
最新的release中ctrlc能够强制退出shell/sshmode
