### ISSUE TITLE
端口复用怎么用？

### ISSUE THREAD

**Issue by wgf4242** [ph4ntonn/Stowaway#68]
```
主要支持windows、mac环境下的复用，linux亦可，但限制较多

admin端：./stowaway_admin -c 192.168.0.105:80 -s 123
agent端：./stowaway_agent  --report 80 --rehost 192.168.0.105 -s 123

```
没看懂啊。。试了下也没明白。请举例吧。
比如 Http有80端口开放。这个agent还是admin怎样复用这个80端口？

**Comment by ph4ntonn** [comment]
agent来复用端口
rehost就是你希望复用的具体地址，report就是复用的端口
具体可以参看https://ph4ntonn.github.io/Port-reuse.html

**Comment by wgf4242** [comment]
> agent来复用端口 rehost就是你希望复用的具体地址，report就是复用的端口 具体可以参看https://ph4ntonn.github.io/Port-reuse.html

3q.
建立代理能复用端口么。试了下没成功。。

**Comment by ph4ntonn** [comment]
没太懂，你的意思是开启socks代理的时候，启动服务的端口要复用？
