### ISSUE TITLE
建议加入睡眠及唤醒设置

### ISSUE THREAD

**Issue by helinze** [ph4ntonn/Stowaway#8]
东西很不错的，实战中有时为避免惊动，需要设置sleep，避免流量过多，同时因为设置sleep后，必然需要唤醒，或者调整sleep为0,。

**Comment by ph4ntonn** [comment]
首先谢谢你的建议～
不知道我理解的是否正确
但在实战中，在使用者不使用stowaway的时间段，在“休眠”状态的stowaway几乎没有流量从节点间通过
所以窃以为sleep操作可能不是必须的？
